void get_name(char* _name);
void get_birth(char* _birth_date);
void get_cpf(double* _cpf);
void get_email(char* _email);
void get_tel(double* _tel);
void get_oab(char* _oab);
void get_role(char* _role);
void get_desc(char* _desc);
void get_available_at(char* _available_at);